name: Docker Compose Deploy CI-CD

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker compose up
    - name: Build the Docker image
      id: check
      run: docker ps      
    - name: Build the Docker image
      id: test
      run: curl -v http://localhost:3000/ 
