name: Docker Compose Deploy CI-CD

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
          docker compose up
    - name: Build the Docker image
      id: check
      run: docker ps      
    - name: Build the Docker image
      id: test
      run: curl -v http://localhost:3000/ 
